export const SET_LOCATION = "SET_LOCATION";
export const SET_LOCATION_PERMISSION = "SET_LOCATION_PERMISSION";
export const SET_GROUP_VIEW = "SET_GROUP_VIEW";
export const GET_GROUP_VIEW = "GET_GROUP_VIEW";
export const SET_LOCATION_ERROR = "SET_LOCATION_ERROR";
export const SEND_UPDATE = "SEND_UPDATE";